package com.amcolabs.quizapp.databaseutils;

import com.j256.ormlite.field.DatabaseField;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class UserPreferences {

	// messageId is generated by the database and set on the object automagically
	@DatabaseField(id=true, index = true)
	String property;
	@DatabaseField
	String data;
	

	UserPreferences() {
		// needed by ormlite
	}

	public UserPreferences(String property,String data) {
		this.property = property;
		this.setData(data);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(", ").append("property=").append(property);
		sb.append(", ").append("data=").append(getData());
		return sb.toString();
	}

	public String getData() {
		return data;
	}

	public void setData(String data) {
		this.data = data;
	}
}